# Generated by Django 2.2.2 on 2019-06-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20190609_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
